### ISSUE TITLE
发现一处安全性问题

### ISSUE THREAD

**Issue by DiangD** [373675032/moti-cloud#2]
![image](https://user-images.githubusercontent.com/48688378/77083646-cd1a7f00-6a38-11ea-992e-087f874d40c5.png)
复现：这里我创建了一个账号并创建了几个文件夹。如果我用另一个用户访问这个文件夹的url，是可以访问到的。
![image](https://user-images.githubusercontent.com/48688378/77084056-621d7800-6a39-11ea-875b-bec644c2998a.png)

**Comment by DiangD** [comment]
甚至可以下载别人网盘里的资源

**Comment by DiangD** [comment]
甚至可以下载别人网盘的资源

**Comment by 373675032** [comment]
好的，马上修复，感谢

**Comment by 373675032** [comment]
解决方法：
在访问指定文件夹时，如果传入的文件夹ID存在，那么需要判断此文件夹所属文件仓库是否与当前登录用户文件仓库的ID一致。如果不一致跳转到其他页面（可以是错误页面，或者是根目录）；如果一致，继续原来的流程。
