### ISSUE TITLE
qq登录回调accessToken为空

### ISSUE THREAD

**Issue by waiting-windy** [373675032/moti-cloud#3]
我也看了您的博客，不是那个原因，但是错误地方一样。不知道怎么回事

**Comment by 373675032** [comment]
应该就是这些配置信息没有配置好啊，其他人都没事




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nanfeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 晚上9:04
收件人:&nbsp;"373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[373675032/moti-cloud] qq登录回调accessToken为空 (#3)





 
我也看了您的博客，不是那个原因，但是错误地方一样。不知道怎么回事

**Comment by waiting-windy** [comment]
http://lizeyu.club/connection?code=8DD95C0C34C869DCFF12438880C57662&state=ee92ff20944c28e10ccba9b87f926125


这是返回值，按理说不错啊

**Comment by waiting-windy** [comment]
看着不错啊
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"莫提"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 晚上9:06
收件人:&nbsp;"373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;;
抄送:&nbsp;"小泽"<964879015@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [373675032/moti-cloud] qq登录回调accessToken为空 (#3)





 应该就是这些配置信息没有配置好啊，其他人都没事 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"nanfeng"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月2日(星期四) 晚上9:04 
 收件人:&amp;nbsp;"373675032/moti-cloud"<moti-cloud@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[373675032/moti-cloud] qq登录回调accessToken为空 (#3) 
 
 
 
 
 
   
 我也看了您的博客，不是那个原因，但是错误地方一样。不知道怎么回事

**Comment by 373675032** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nanfeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 晚上9:09
收件人:&nbsp;"373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;;
抄送:&nbsp;"小白云盘"<373675032@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [373675032/moti-cloud] qq登录回调accessToken为空 (#3)





 看着不错啊 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"莫提"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月2日(星期四) 晚上9:06 
 收件人:&amp;nbsp;"373675032/moti-cloud"<moti-cloud@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"小泽"<964879015@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [373675032/moti-cloud] qq登录回调accessToken为空 (#3) 
 
 
 
 
 
  应该就是这些配置信息没有配置好啊，其他人都没事  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"nanfeng"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年4月2日(星期四) 晚上9:04  
  收件人:&amp;amp;nbsp;"373675032/moti-cloud"<moti-cloud@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[373675032/moti-cloud] qq登录回调accessToken为空 (#3)  
   
   
   
   
   
     
  我也看了您的博客，不是那个原因，但是错误地方一样。不知道怎么回事

**Comment by 373675032** [comment]
把你QQ互联应用信息截个图我看看，那个回调域这些








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nanfeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 晚上9:09
收件人:&nbsp;"373675032/moti-cloud"<moti-cloud@noreply.github.com&gt;;
抄送:&nbsp;"小白云盘"<373675032@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [373675032/moti-cloud] qq登录回调accessToken为空 (#3)





 看着不错啊 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"莫提"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月2日(星期四) 晚上9:06 
 收件人:&amp;nbsp;"373675032/moti-cloud"<moti-cloud@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"小泽"<964879015@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [373675032/moti-cloud] qq登录回调accessToken为空 (#3) 
 
 
 
 
 
  应该就是这些配置信息没有配置好啊，其他人都没事  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"nanfeng"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年4月2日(星期四) 晚上9:04  
  收件人:&amp;amp;nbsp;"373675032/moti-cloud"<moti-cloud@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[373675032/moti-cloud] qq登录回调accessToken为空 (#3)  
   
   
   
   
   
     
  我也看了您的博客，不是那个原因，但是错误地方一样。不知道怎么回事
