### ISSUE TITLE
作者您好，我发现了代码里一个问题，详情如下

### ISSUE THREAD

**Issue by tonglsh** [373675032/moti-cloud#5]
我在我的图像内尝试删除我之前上传的图片时引发了400，这是浏览器显示的状态：http://localhost:8080/moti-cloud/deleteFile?fId=2&folder=undefined
我发现folder并没有定义，所以我尝试在全部文件下删除这张图片，是成功的。Request URL: http://localhost:8080/moti-cloud/deleteFile?fId=2&folder=0，这里folder是赋值了的。

所以是哪里出现了问题呢，我的js不是很好，请您有空的时候帮个忙，嘿嘿。下面是后台打印的日志：主要问题是Java的类型异常，因为folder被保存成了字符串“undifined”，无法转换成Integer。

Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "undefined"

**Comment by tonglsh** [comment]
补充，只要在分类文件下删除就会引发（不仅仅是我的图像）

**Comment by 373675032** [comment]
#### 你现在的版本应该是第一个版本（最开始的版本），我之前设计这个功能的思路是这样的，deleteFile需要传递两个参数一个是文件ID，也就是fId，用来删除具体文件，另一个是父文件夹ID（folder，如果是用户根目录，则folder为0），这个folder是通过前端获取的，folder这个参数主要用来控制页面的跳转，当我们在某一个文件夹下删除文件的时候，删除之后肯定还要跳转回到这个文件夹。然而分类文件是把所有同类的文件都聚集到一起了，所以前端就不知道父文件夹是哪个了，就会出现folder=undefined这种情况。后端接收不到folder这个值（整数类型），所以就会报请求无效错误（400）。
------------------
其实在第二个版本我直接把在分类文件中删除、重命名的操作删除了，当然可以加一些业务逻辑的处理实现这些功能，我偷了个懒

**Comment by tonglsh** [comment]
我后来去你的博客里发现你把这个功能删除了，哈哈明白了
